---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: example
  annotations:
    # Assuming that this will be for a domain that we actually own,
    # we could use the 'letsencrypt-production' issuer to get
    # a real certificate.
    # The 'letsencrypt-staging' issuer will get us a fake certificate.
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    #cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - example.com
    secretName: examplecom-tls
  rules:
  - host: example.com
    http:
      paths:
      - path: /tamedia
        backend:
          serviceName: greeter-tamedia
          servicePort: 11130
