---
apiVersion: v1
kind: Service
metadata:
  name: greeter-tamedia
  labels:
    app.kubernetes.io/name: greeter-tamedia
spec:
  type: NodePort
  selector:
    app: greeter-tamedia
  ports:
  - port: 11130
